language: node_js

node_js:
 - stable

services:
  - postgresql

env:
  global:
    - POSTGRES_HOST=localhost
    - POSTGRES_PORT=5432

addons:
  sonarcloud:
    organization: "michelmotta"
    token:
      secure: "dH74bDlipLBhKj+Imo4TA+t79SOFkaNuL/uR/1VKaC/lm5PQm+TnLQQapIEmSQAK0M54s96gA92RwxLlBb6BW3GRvlQjemsK+l8MtyNM2fHHgNwfXu8bjoDXrrQFnt0xsaIcUqEcCiwTQUzxiwG6P3Wb+SALQ0ZCSs+n8lAoKchzr8QrVq8klXbPPuydze+FQPOOHIUhuBK1O55jBqlWj+M2zZJHjRrm7iA2nfeXAdiNqU2lOgsI6DY2+U0p9CXgCfhxTOvsEFZXK8wbywnSDleGS/TGeG8C1ykLxpnl7NCtZIz10t89pAjnRsBExm2iH4VTbxwMqWjDglBWgFpbcYD6mIOooxEEVmtqrQ6CLh1ZQV8Z/I+u7xSU/vBmesst1KZXM2rYrF/p1NfVrFr4TBrum4I6qty4414Pod0QT5ldjzw3AWlspTWVIXY9vUfVO84UHCbZDZhHjjC+2bgxoaxhYTwF3Db4WIyvn2Oz7MN7XxI4hqOWToG0DYQuM/Gs3bYxNGX49f0MSO62RW/Vrt74alDp0pCB5ipw1CK0AO6TL3PXDipNvjfP92WCrBPUF2R1H4Kq+oYMpCFq+hnjqT4rKoHHD2/Ri7+XTml8NiOheiweEpkVsyqPUMmgZUoIPu/4vT2uSid/jl4JoeBBLBxsoMZZpysjEaSYMM/gpJM="

install:
  - npm install

script:
  - npm test
  - sonar-scanner